# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: v3.0.2
    hooks:
      - name: Prettier
        id: prettier
        # Temporary excludes so we can gradually normalize the formatting
        exclude: >
          (?x)^(
            .pre-commit-config.yaml
          )$
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
          - prettier-plugin-sort-json
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - name: Fix End Of File
        id: end-of-file-fixer
      - name: Fix Trailing Spaces
        id: trailing-whitespace
      - name: Fix Mixed Line Endings
        id: mixed-line-ending
      - name: Fix UTF-8
        id: fix-byte-order-marker
      - name: Check Merge Conflicts
        id: check-merge-conflict
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.5
  #   hooks:
  #     - name: Codespell
  #       id: codespell
  #       additional_dependencies:
  #         - tomli

  - repo: local
    hooks:
      - id: powershell-script  # Choose a descriptive ID
        name: Run PowerShell script
        entry: pwsh -Command ".\pre-commit.ps1"  # Invoke PowerShell
        language: system  # Mark as system language
        pass_filenames: false  # Don't pass filenames by default
        always_run: true  # Run on every commit
        files: ''  # Run on all files (adjust as needed)
        stages: [commit]  # Run during the commit stage
        verbose: false

  # -   id: powershell_scriptanalyzer
  #     name: Powershell lint with PSScriptAnalyzer
  #     description: This runs PSScriptAnalyzer on your powershell files
  #     entry: pre-commit powershell_scriptanalyzer
  #     language: script
  #     files: ^.*\.ps1$
  #     types: [text]
  #     entry: pwsh -Command "Invoke-ScriptAnalyzer -Settings PSGallery -Recurse -ReportSummary -EnableExit -Path ."
  #     require_serial: false
  #     additional_dependencies: []
  #     minimum_pre_commit_version: '0'
  #     pass_filenames: false
